### ISSUE TITLE
Use escaping for brackets causes a crash

### ISSUE THREAD

**Issue by SergejPr** [RedMadRobot/input-mask-android#104]
### Prerequisites

* [X] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-android/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-android#knownissues) section;
  * checked that my issue isn't already [filled](https://github.com/RedMadRobot/input-mask-android/issues?q=is%3Aissue);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Describe the bug:
Use escaping for brackets e.g. "+7 ([000]) \\\\[[000]-[00]-[00]" causes a crash

### Steps to reproduce the behaviour:

1. Use mask with escaped brackets, e.g. "+7 ([000]) \\\\[[000]-[00]-[00]"
2. Start enter data

**Expected behaviour**
Application correct handles escaped brackets

**Actual behaviour**
App crashes when reach escaped bracket 

**Platform information**
 - OS version: Android 9, 10
 - Library version: 6.0.0
 - Device (if bug is device-specific): -

**Additional context**
Crashlog:
```
2020-06-24 12:11:58.787 13724-13724/com.redmadrobot.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.redmadrobot.sample, PID: 13724
    java.lang.IndexOutOfBoundsException: setSpan (10 ... 10) ends beyond length 9
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1321)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:682)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:674)
        at android.text.Selection.setSelection(Selection.java:93)
        at android.text.Selection.setSelection(Selection.java:77)
        at android.text.Selection.setSelection(Selection.java:152)
        at android.widget.EditText.setSelection(EditText.java:136)
        at com.redmadrobot.inputmask.MaskedTextChangedListener.afterTextChanged(MaskedTextChangedListener.kt:193)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:9812)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:12600)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1273)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:576)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:506)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:36)
        at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:131)
        at android.widget.TextView.doKeyDown(TextView.java:7707)
        at android.widget.TextView.onKeyDown(TextView.java:7484)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2709)
        at android.view.View.dispatchKeyEvent(View.java:12463)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:432)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3425)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:108)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:126)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:346)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5203)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5071)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4590)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4643)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4609)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4749)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4617)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4806)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4590)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4643)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4609)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4617)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4590)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7318)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7287)
2020-06-24 12:11:58.788 13724-13724/com.redmadrobot.sample E/AndroidRuntime:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7248)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4360)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2020-06-24 12:11:58.847 13724-13724/com.redmadrobot.sample I/Process: Sending signal. PID: 13724 SIG: 9

```

**Comment by taflanidi** [comment]
Hey @SergejPr,
Thanks for the report.

While I'm looking into this, could you please describe any real cases replicating this bug just for the reference?

**Comment by Grue1ing** [comment]
Hi i had the same problem. I solved it by replacing the keyboard with another type. In certain keyboards, some characters are prohibited that can be added to the mask. If you put autocomplete = true, it will crash.

**Comment by taflanidi** [comment]
Closing due to inactivity.
