### ISSUE TITLE
Сrashes while trying to delete a character

### ISSUE THREAD

**Issue by indrih17** [RedMadRobot/input-mask-android#105]
**Code**:
```kotlin
fun EditText.configurePortionEditText(): TextWatcher {
    inputType = InputType.TYPE_CLASS_NUMBER
    keyListener = DigitsKeyListener.getInstance("0123456789 -.")
    filters += InputFilterMinMax { portion -> portion.toIntOrNull()?.let { it in 10..3000 } }
    val watcher = MaskedTextChangedListener(field = this, primaryFormat = "[0099]")
    addTextChangedListener(watcher)
    return watcher
}

inline class InputFilterMinMax(private val isInRange: (String) -> Boolean?) : InputFilter {
    override fun filter(
        source: CharSequence,
        start: Int,
        end: Int,
        dest: Spanned,
        destStart: Int,
        destEnd: Int
    ): CharSequence? {
        val destStringify = dest.toString()
        // Remove the string out of destination that is to be replaced
        val firstPart = if (destStart > 0) destStringify.substring(0, destStart) else ""
        val secondPart = if (destStringify.length > destEnd) destStringify.substring(destEnd, destStringify.length) else ""
        // Add the new string in
        val withSource = firstPart + source.toString() + secondPart
        return if (isInRange(withSource) != false) null else ""
    }
}
```

**Description**:
The default value is 100. We erase the first zero, then the second - there is a crash.

**Stacktrace**: 
```text
java.lang.IndexOutOfBoundsException: setSpan (1 ... 1) ends beyond length 0
    at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1321)
    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:682)
    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:674)
    at android.text.Selection.setSelection(Selection.java:93)
    at android.text.Selection.setSelection(Selection.java:77)
    at android.text.Selection.setSelection(Selection.java:152)
    at android.widget.EditText.setSelection(EditText.java:136)
    at com.redmadrobot.inputmask.MaskedTextChangedListener.afterTextChanged(MaskedTextChangedListener.kt:193)
    at android.widget.TextView.sendAfterTextChanged(TextView.java:9770)
    at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:12522)
    at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1273)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:576)
    at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
    at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:36)
    at android.text.method.BaseKeyListener.backspaceOrForwardDelete(BaseKeyListener.java:370)
    at android.text.method.BaseKeyListener.backspace(BaseKeyListener.java:71)
    at android.text.method.BaseKeyListener.onKeyDown(BaseKeyListener.java:479)
    at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:148)
    at android.widget.TextView.doKeyDown(TextView.java:7665)
    at android.widget.TextView.onKeyDown(TextView.java:7442)
    at android.view.KeyEvent.dispatch(KeyEvent.java:2692)
    at android.view.View.dispatchKeyEvent(View.java:12450)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
    at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:428)
    at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
    at android.app.Activity.dispatchKeyEvent(Activity.java:3360)
    at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
    at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
    at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
    at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
    at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
    at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:342)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5037)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4905)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
```

**Comment by Miha-x64** [comment]
This happens to me with absolutely default setup:
```kt
addView(editText {
  layoutParams = …
  hint = …
  setHintTextColor(…)
  MaskedTextChangedListener.installOn(this, "+7 ([000]) [000]-[00]-[00]")
//  inputType = InputType.TYPE_CLASS_NUMBER // uncomment me—and you're crashed
//  keyListener = DigitsKeyListener.getInstance("0123456789") // uncomment me—and you're crashed
})
```
Falling back to any older version doesn't help.

**Comment by taflanidi** [comment]
Hey @indrih17,
Thanks for your report.

Could you please elaborate a little on the behaviour you're trying to achieve?

**Comment by kramsretep** [comment]
Hi - I'm seeing this issue also. What I did was tap the "delete" key in the keyboard, then typed two characters - the crash happened on typing the second character.

From a brief debugging attempt, I think something wrong is happening in MaskedTextChangeListener.onTextChanged(...). It looks like this.caretPosition has a value one larger than it ought to be.

For context, this is happening on an EditText I configured to be a credit card expiration date, like this:

		installOn(
				binding.expiration,
				"[00]{/}[00]",
				object: ValueListener {
					override fun onTextChanged(maskFilled: Boolean, extractedValue: String, formattedValue: String) {
						Timber.d(extractedValue)
						Timber.d(maskFilled.toString())
					}
				}
		)

This doesn't happen in an EditText configured for the credit card number, which I did like this:

		installOn(
				binding.cardNumber,
				"[0000] [0000] [0000] [0000]",
				listOf("4[000] [0000] [0000] [0000]", "5[000] [0000] [0000] [0000]",
						"[0000] [000000] [00000]", "3[000] [000000] [00000]",
						"6[000] [0000] [0000] [0000]"),
				AffinityCalculationStrategy.CAPACITY,
				object: ValueListener {
					override fun onTextChanged(maskFilled: Boolean, extractedValue: String, formattedValue: String) {
						Timber.d(extractedValue)
						Timber.d(maskFilled.toString())
					}
				}
		)

**Comment by gorodechnyj** [comment]
@Miha-x64 This can happen because of wrong `android:digits` attribute setup. Check that you have added all mask symbols, like plus, minus sign and brackets

**Comment by taflanidi** [comment]
Closing due to inactivity.
