### ISSUE TITLE
IndexOutOfBoundsException: setSpan (17 ... 17) ends beyond length 2

### ISSUE THREAD

**Issue by SteelOscar** [RedMadRobot/input-mask-android#114]
### Describe the bug
I use MaskedTextChangedListener to format the phone number, the mask is +7 ([000]) [000] - [00] - [00].
With normal manual text input, everything works fine, but if you use the setTex method, the listener throws an exception

java.lang.IndexOutOfBoundsException: setSpan (17 ... 17) ends beyond length 2
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
        at android.text.Selection.setSelection(Selection.java:94)
        at android.text.Selection.setSelection(Selection.java:78)
        at android.text.Selection.setSelection(Selection.java:153)
        at android.widget.EditText.setSelection(EditText.java:136)
        at com.redmadrobot.inputmask.MaskedTextChangedListener.afterTextChanged(MaskedTextChangedListener.kt:193)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10551)
        at android.widget.TextView.setText(TextView.java:6278)
        at android.widget.TextView.setText(TextView.java:6097)
        at android.widget.EditText.setText(EditText.java:122)

 - Library version: 6.0.0

**Comment by SteelOscar** [comment]
bug fixes MaskedTextChangedListener
<img width="842" alt="Снимок экрана 2021-09-17 в 13 37 41" src="https://user-images.githubusercontent.com/47324130/133752253-0942a562-ac3d-4ef3-9020-e1328d71556a.png">

**Comment by SteelOscar** [comment]
fix it in new version of the library

**Comment by taflanidi** [comment]
Fixed in `6.1.0`.

**Comment by osipxd** [comment]
@apolloandroid, 6.1.0 is released on JitPack
