### ISSUE TITLE
Do I have to implement a listener to get the value without mask?

### ISSUE THREAD

**Issue by salazarwagner** [RedMadRobot/input-mask-android#25]
I read this "[00]-[00] and [00]{-}[00] will format the input to the same form of 12-34, but in the first case the value, extracted by the library, will be equal to 1234, and in the second case it will result in 12-34""

So, I'm doing something like this:

        final MaterialEditText test1 = (MaterialEditText) view.getRootView().findViewById(R.id.test1);
        final MaskedTextChangedListener test1Listener = new MaskedTextChangedListener(
                "[00]-[00]",true, test1, null, null );
        test1.addTextChangedListener(test1Listener);
        test1.setOnFocusChangeListener(test1Listener);
        test1.setHelperText(test1Listener.placeholder());

        final MaterialEditText test2 = (MaterialEditText) view.getRootView().findViewById(R.id.test2);
        final MaskedTextChangedListener test2Listener = new MaskedTextChangedListener(
                "[00]{-}[00]",true, test2, null, null );
        test2.addTextChangedListener(test2Listener);
        test2.setOnFocusChangeListener(test2Listener);
        test2.setHelperText(test2Listener.placeholder());

In both case I got something like XX-XX, when I call test1.getText(). What I'm doing wrong? thxs for help.

**Comment by taflanidi** [comment]
@salazarwagner, thanks for your question.

Our library doesn't have anything with `EditText` (or `MaterialEditText`) behaviour. This means it doesn't override `getText()` or any other SDK method of the `EditText`, such that when you are calling `test1.getText()` — you will simply receive the text contained inside the control, nothing different from the default implementation. 

Please, pay close attention to our README docs. There, we provided an example of how to deal with the library's `MaskedTextChangedListener`:
```java
final EditText editText = (EditText) findViewById(R.id.edit_text);
final MaskedTextChangedListener listener = new MaskedTextChangedListener(
    "+7 ([000]) [000] [00] [00]",
    true,
    editText,
    null,
    new MaskedTextChangedListener.ValueListener() { 
        @Override
        public void onTextChanged(boolean maskFilled, @NonNull final String extractedValue) {
            // here, you've got an extractedValue variable containing corresponding text
        }
    }
);
```
`MaskedTextChangedListener` constructor accepts `MaskedTextChangedListener.ValueListener` instance, which will receive callbacks with provided `extractedValue`.
In order to extract value without this callback, you will have to pass your `EditText`'s text through the `Mask` instance, which is attached to the `MaskedTextChangedListener`:
```java
final EditText editText = (EditText) findViewById(R.id.edit_text);
final MaskedTextChangedListener listener = new MaskedTextChangedListener(...);

final Mask.Result result = listener.getMask().apply(
    new CaretString(
        editText.getText().toString(), 
        editText.getText().length()
    ),
    true
);

final String extractedValue = result.getExtractedValue();
```
— or you may use a standalone `Mask` instance ad lib.

**Comment by btow** [comment]
I tried to implement the listener as follows:
`        final MaskedTextChangedListener mCadNumChangedListener = new MaskedTextChangedListener(
                "[09]{:}[09]{:}[09999]{:}[0999]",
                true,
                etAddressItemFrag1_1,
                null,
                new MaskedTextChangedListener.ValueListener() {
                    @Override
                    public void onTextChanged(boolean maskFilled,
                                              @NonNull final String extractedValue) {
                        Logger.writeText(LOG_TAG, extractedValue);
                        Logger.writeText(LOG_TAG, String.valueOf(maskFilled));
                    }
                }
        );
        textInputLayout.setHint(getString(R.string.frag1_1_t0)
                + mCadNumChangedListener.placeholder());
        etAddressItemFrag1_1.requestFocus();
        etAddressItemFrag1_1.setInputType(InputType.TYPE_CLASS_NUMBER);
        etAddressItemFrag1_1.addTextChangedListener(mCadNumChangedListener);
        etAddressItemFrag1_1.setOnFocusChangeListener(mCadNumChangedListener);
`
After entering the second character in the field, my application drops. In this case, the console displays the following:

> I/Frag1_1: >>--------------------------------------------------------------------->>
I/Frag1_1: 66:
I/Frag1_1: >>--------------------------------------------------------------------->>
I/Frag1_1: false
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ru.reestore.app, PID: 26906
                  java.lang.IndexOutOfBoundsException: setSpan (3 ... 3) ends beyond length 2
                      at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1283)
                      at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:699)
                      at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:692)
                      at android.text.Selection.setSelection(Selection.java:76)
                      at android.text.Selection.setSelection(Selection.java:87)
                      at android.widget.EditText.setSelection(EditText.java:109)
                      at com.redmadrobot.inputmask.MaskedTextChangedListener.afterTextChanged(MaskedTextChangedListener.kt:113)
                      at android.widget.TextView.sendAfterTextChanged(TextView.java:8547)
                      at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10756)
                      at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1236)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:592)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:520)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:519)
                      at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
                      at android.widget.TextView.doKeyDown(TextView.java:6415)
                      at android.widget.TextView.onKeyDown(TextView.java:6205)
                      at android.view.KeyEvent.dispatch(KeyEvent.java:2693)
                      at android.view.View.dispatchKeyEvent(View.java:10053)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:384)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1660)
                      at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:429)
                      at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
                      at android.app.Activity.dispatchKeyEvent(Activity.java:3023)
                      at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
                      at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
                      at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:336)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4821)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4786)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4297)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4350)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4316)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4463)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4324)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4520)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4297)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4350)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4316)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4324)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4297)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6853)
E/AndroidRuntime:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6827)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6770)
                      at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4083)
                      at android.os.Handler.dispatchMessage(Handler.java:110)
                      at android.os.Looper.loop(Looper.java:203)
                      at android.app.ActivityThread.main(ActivityThread.java:6293)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
