### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by dimmduh** [RedMadRobot/input-mask-android#32]
`
                                                          
                                                                  java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 2
                                                                      at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1094)
                                                                      at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:669)
                                                                      at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:662)
                                                                      at android.text.Selection.setSelection(Selection.java:123)
                                                                      at android.text.Selection.setSelection(Selection.java:134)
                                                                      at android.widget.EditText.setSelection(EditText.java:128)
                                                                      at com.redmadrobot.inputmask.MaskedTextChangedListener.afterTextChanged(MaskedTextChangedListener.kt:113)
                                                                      at android.widget.TextView.sendAfterTextChanged(TextView.java:9269)
                                                                      at android.widget.TextView.setText(TextView.java:5008)
                                                                      at android.widget.TextView.setText(TextView.java:4826)
                                                                      at android.widget.EditText.setText(EditText.java:114)
                                                                      at android.widget.TextView.setText(TextView.java:4801)
                                                                      at com.redmadrobot.inputmask.MaskedTextChangedListener.onFocusChange(MaskedTextChangedListener.kt:154)
                                                                      at android.view.View.onFocusChanged(View.java:6259)
                                                                      at android.widget.TextView.onFocusChanged(TextView.java:9519)
                                                                      at android.widget.EditText.onFocusChanged(EditText.java:203)
                                                                      at android.view.View.handleFocusGainInternal(View.java:5985)
                                                                      at android.view.View.requestFocusNoSearch(View.java:9058)
                                                                      at android.view.View.requestFocus(View.java:9037)
                                                                      at android.view.View.requestFocus(View.java:9004)
                                                                      at android.view.View.requestFocus(View.java:8983)
                                                                      at android.support.v7.widget.RecyclerView.recoverFocusFromState(RecyclerView.java:3411)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3633)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3275)
                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                      at android.view.View.layout(View.java:17945)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                      at android.view.View.layout(View.java:17945)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                      at android.widget.ScrollView.onLayout(ScrollView.java:2402)
                                                                      at android.view.View.layout(View.java:17945)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                      at android.view.View.layout(View.java:17945)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                      at android.view.View.layout(View.java:17945)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                      at android.view.View.layout(View.java:17945)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                      at android.view.View.layout(View.java:17945)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                      at android.view.View.layout(View.java:17945)
                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  	at android.widget.FrameLayout.layoutChildren(FrameLayou

format "+7 ([000]) [000] [00] [00]";

the error comes after showing alert

**Comment by dimmduh** [comment]
with this mask - works "+7[0000000000]"
I use it in recycler view

**Comment by taflanidi** [comment]
Hey @dimmduh!
Please, read carefully the [Known issues: InputMask vs. android:inputType](https://github.com/RedMadRobot/input-mask-android#inputmask-vs-androidinputtype) section of the README as it looks like you are trying to use `numeric` input type without providing correct acceptable `digits` (space, braces and the plus sign).

**Comment by dimmduh** [comment]
Still randomly crashes
[00000000000000]
tested with
                android:inputType="number"
                android:digits="0123456789+-() []"

**Comment by taflanidi** [comment]
@dimmduh, is it still an `IndexOutOfBoundsException`?

Without concrete steps to reproduce your issue we won't be able to diagnose it, I'm afraid. Every detail matters, including such things like device locale and vendor. 

From our practice, most of the crashes reported by our library users were actually caused by the misuse of the SDK.
