### ISSUE TITLE
Crash if – ("en dash") character is used instead of -

### ISSUE THREAD

**Issue by ozbek** [RedMadRobot/input-mask-android#38]
E.g., using `+7 ([000]) [000]–[0000]` instead of `+7 ([000]) [000]-[0000]` causes crash. Is `–` a special character within the library?

**Comment by taflanidi** [comment]
Hi @ozbek 
Thanks for your crash report.

I'll need to look into it, so stay tuned as I'll come back to you a little bit later.

Meanwhile, I'd be glad for your help if you could bring the actual crash log, thanks in advance!

**Comment by ozbek** [comment]
Hello @taflanidi.
Thanks for the quick response. Please see below for the stack trace:

    Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 3
    at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1309)
    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
    at android.text.Selection.setSelection(Selection.java:76)
    at android.text.Selection.setSelection(Selection.java:87)
    at android.widget.EditText.setSelection(EditText.java:127)
    at com.redmadrobot.inputmask.MaskedTextChangedListener.afterTextChanged(MaskedTextChangedListener.kt:113)
    at android.widget.TextView.sendAfterTextChanged(TextView.java:9375)
    at android.widget.TextView.setText(TextView.java:5401)
    at android.widget.TextView.setText(TextView.java:5248)
    at android.widget.EditText.setText(EditText.java:113)
    at android.widget.TextView.setText(TextView.java:5205)
    at com.redmadrobot.inputmask.MaskedTextChangedListener.onFocusChange(MaskedTextChangedListener.kt:154)
    at android.view.View.onFocusChanged(View.java:6921)
    at android.widget.TextView.onFocusChanged(TextView.java:9601)
    at android.view.View.handleFocusGainInternal(View.java:6593)
    at android.view.View.requestFocusNoSearch(View.java:10823)
    at android.view.View.requestFocus(View.java:10802)
    at android.view.View.requestFocus(View.java:10769)
    at android.view.View.requestFocus(View.java:10711)
    at android.view.View.onTouchEvent(View.java:12963)
    at android.widget.TextView.onTouchEvent(TextView.java:9660)
    at android.view.View.dispatchTouchEvent(View.java:11721)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
    at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:445)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1828)
    at android.app.Activity.dispatchTouchEvent(Activity.java:3292)
    at com.example.MainActivity.dispatchTouchEvent(VoiceAndDataActivity.java:94)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
    at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:407)
    at android.view.View.dispatchPointerEvent(View.java:11960)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4776)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4590)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4274)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4331)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6642)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6616)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6577)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6745)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
    at android.os.MessageQueue.next(MessageQueue.java:325)
    at android.os.Looper.loop(Looper.java:142)
    at android.app.ActivityThread.main(ActivityThread.java:6541)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by taflanidi** [comment]
@ozbek, just to make sure, did you consider applying [this workaround](https://github.com/RedMadRobot/input-mask-android#inputmask-vs-androidinputtype) (a known issue about input type)?

**Comment by ozbek** [comment]
Thanks @taflanidi, it's totally that issue. Sorry for the false alarm.

**Comment by taflanidi** [comment]
@ozbek great!
