### ISSUE TITLE
Add contributing guide, issue and pull request templates.

### ISSUE THREAD

**Issue by taflanidi** [RedMadRobot/input-mask-android#42]
Subject.

Consider reading official [GitHub docs](https://github.com/blog/2111-issue-and-pull-request-templates).

**Comment by oreis91** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: br.com.bcarros, PID: 727
                  java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
                      at com.redmadrobot.inputmask.ReversedMaskTextChangedListener.<init>(ReversedMaskTextChangedListener.kt)
                      at br.com.bcarros.apk.InstitutionalFinanceActivity.onCreate(InstitutionalFinanceActivity.java:170)
                      at android.app.Activity.performCreate(Activity.java:6955)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6776)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by belinsky** [comment]
same problem, but on android 6.x.x. (8.0.1 is ok)

**Comment by taflanidi** [comment]
Hey @oreis91, @belinsky,
Please file a separate issue report. I'll be able to investigate subject later this week. 

Shallow search [suggests](https://stackoverflow.com/questions/44197521/gradle-project-java-lang-noclassdeffounderror-kotlin-jvm-internal-intrinsics) you might need to explicitly configure Kotlin dependency in your project. Please let me know, if it works.
