### ISSUE TITLE
bug  java.lang.IndexOutOfBoundsException:

### ISSUE THREAD

**Issue by Anton22255** [RedMadRobot/input-mask-android#44]
java.lang.IndexOutOfBoundsException: setSpan (11 ... 11) ends beyond length 10
                                                                        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1265)
                                                                        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
                                                                        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
                                                                        at android.text.Selection.setSelection(Selection.java:76)
                                                                        at android.widget.TextView.semSetSelection(TextView.java:11571)
                                                                        at android.widget.TextView.semSetSelection(TextView.java:11585)
                                                                        at android.widget.EditText.setSelection(EditText.java:125)
                                                                        at com.redmadrobot.inputmask.MaskedTextChangedListener.afterTextChanged(MaskedTextChangedListener.kt:113)
                                                                        at android.widget.TextView.sendAfterTextChanged(TextView.java:9508)
                                                                        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:12460)
                                                                        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
                                                                        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
                                                                        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
                                                                        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
                                                                        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:850)
                                                                        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:200)
                                                                        at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
                                                                        at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:158)
                                                                        at com.android.tools.profiler.support.event.InputConnectionWrapper.commitText(InputConnectionWrapper.java:43)
                                                                        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:345)
                                                                        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:91)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by ozbek** [comment]
@Anton22255 

Try [InputMask vs. `android:inputType`](https://github.com/RedMadRobot/input-mask-android#inputmask-vs-androidinputtype) issue mentioned in the readme and try the workaround.

**Comment by taflanidi** [comment]
Hi @Anton22255,
I'm just checking in. Is this issue still valid?

**Comment by CoolMind** [comment]
Very bad. I also have this exception: `java.lang.IndexOutOfBoundsException: setSpan (7 ... 7) ends beyond length 1`. A problem is I want to change a keyboard from _text_ to _numeric_ and vise versa depending on cursor position. `inputType = InputType.TYPE_CLASS_NUMBER` and `keyListener = DigitsKeyListener.getInstance("0123456789")` don't solve.

**Comment by NicolasGodfather** [comment]
In my case, for avoid crash java.lang.IndexOutOfBoundsException in the class MaskedTextChangedListener  - me help only this way:

> class CustomMaskedTextChangedListener(format: String, autocomplete: Boolean, field: EditText, listener: TextWatcher?, valueListener: MaskedTextChangedListener.ValueListener?): MaskedTextChangedListener(format, autocomplete, field, listener, valueListener) {
>     override fun afterTextChanged(edit: Editable?) {
>         try {
>             super.afterTextChanged(edit)
>         } catch (e: Exception) {
>             e.message
>         }
>     }
> }

**Comment by ozbek** [comment]
Catching a generic exception is not really a _solution_ per se.

**Comment by hardikamal** [comment]
I am still facing this issue. Any solution found?

**Comment by CoolMind** [comment]
This primitive library very likely won't have a solution.

**Comment by taflanidi** [comment]
Hey @hardikamal 
We've introduced some major updates, including a fix for [this](https://stackoverflow.com/questions/57937110/application-crash-when-delete-digits-redmarobot-input-mask) particular crash on deletion/backspacing.

Please, give it a try!

P.s. Should you have any issues, please do not hesitate to open **new** tickets instead of commenting on the closed ones.

**Comment by CoolMind** [comment]
This primitive library again changed it's name. Now it's `implementation 'com.redmadrobot:input-mask-android:5.0.0'`.
