### ISSUE TITLE
Crash in pure Java project

### ISSUE THREAD

**Issue by gmk57** [RedMadRobot/input-mask-android#57]
Hello & thanks for the most flexible input mask for Android! :+1: 
It seems that recent versions of the library don't support pure Java projects (without Kotlin): initialization constantly fails with NoClassDefFoundError.
Tested on 3.2.0, 3.3.0, 3.4.0. Version 2.3.1 works fine.
If Java support was dropped intentionally, maybe it should be stated clearly in Readme?
Probably the same problem is mentioned in [#42](https://github.com/RedMadRobot/input-mask-android/issues/42#issuecomment-385688673) and [#52](https://github.com/RedMadRobot/input-mask-android/issues/52#issuecomment-385246573).
[Very simple demo project.](https://github.com/gmk57/InputMaskTest)
Full stacktrace:
```
05-24 23:06:03.089 3192-3192/gmk57.inputmasktest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: gmk57.inputmasktest, PID: 3192
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.redmadrobot.inputmask.MaskedTextChangedListener.<init>(MaskedTextChangedListener.kt)
        at gmk57.inputmasktest.MainActivity.onCreate(MainActivity.java:19)
        at android.app.Activity.performCreate(Activity.java:6723)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/gmk57.inputmasktest-1/base.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_dependencies_apk.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_slice_0_apk.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_slice_1_apk.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_slice_2_apk.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_slice_3_apk.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_slice_4_apk.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_slice_5_apk.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_slice_6_apk.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_slice_7_apk.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_slice_8_apk.apk", zip file "/data/app/gmk57.inputmasktest-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/gmk57.inputmasktest-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.redmadrobot.inputmask.MaskedTextChangedListener.<init>(MaskedTextChangedListener.kt) 
        at gmk57.inputmasktest.MainActivity.onCreate(MainActivity.java:19) 
        at android.app.Activity.performCreate(Activity.java:6723) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6121) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

**Comment by taflanidi** [comment]
Hey @gmk57!
Thanks a lot for your report.

To be honest, I didn't expect this library to be able to operate without Kotlin runtime at all. Lots of logic happens around Kotlin `String`s; primitives have a Kotlin origin, too.

I'll be investigating this issue further in order to make sure everything works as intended. It seems there's a lost dependency issue.

**Comment by taflanidi** [comment]
Alright, let me share my current findings on this.

1. `kotlin-stdlib` dependency gets ditched for `com.redmadrobot:inputmask`;
2. Declaring `kotlin-stdlib` as an "explicit" `api` dependency didn't work;
3. Updating Bintray publishing plugin in order to ensure latest `gradle` version is used didn't work;
4. Dependency tree analysis shows `com.redmadrobot:inputmask` doesn't have any dependencies;
5. The issue is [common](https://www.google.ru/search?q=Failed+resolution+of%3A+Lkotlin%2Fjvm%2Finternal%2FIntrinsics) amongst Kotlin libraries:
a. [Fetch](https://github.com/tonyofrancis/Fetch/issues/100): changing to `api` didn't work
b. [Konfetti](https://github.com/DanielMartinus/Konfetti/issues/47): extending `sourceSets` didn't work

I'm going to include additional instructions into the README for now, leaving this as a known issue. Unfortunately.

**Comment by vkotovv** [comment]
@taflanidi Thanks for the library!  

I think it worth mentioning that you need Kotlin in your project, you should mention it in Usage section, like guys did with Konfetti - https://github.com/DanielMartinus/Konfetti#example-in-java, not just a paragraph in Known issues.

**Comment by taflanidi** [comment]
@vkotovv,
That's a good thought, I'll adjust the readme accordingly.

Please create a separate issue next time. I'll eventually go bonkers trying to track all the reports in closed tickets.
