### ISSUE TITLE
optional number ignored

### ISSUE THREAD

**Issue by jesualex** [RedMadRobot/input-mask-android#59]
Hi!
I'm trying to validate a Chilean rut, 

so I have a mask like this `[90].[000].[000]{-}[_]` in a ReversedMaskTextChangedListener, the problem is that the last digit is ignored so if i write nine digits the last one is deleted then for example if i add **123456789** I get **2.345.678-9** result.

it does not happen if i add a second number required, leaving the mask like this:  `[900].[000].[000]{-}[_]` in this case, if I add **1234567890**, I get **123.456.789-0**

**Comment by jesualex** [comment]
Dear @taflanidi 

it seems to me that the problem is not that, i just eliminated the _ from the mask leaving it like this: `[90].[000].[000]` and the problem continues, if I enter **12345678** I receive in my editText **2.345.678**

**Comment by taflanidi** [comment]
@jesualex, I've reproduced your issue. It has to do with the different count of digits in groups.

May I suggest you a custom `ReversedMaskTextChangedListener` implementation for your needs?
It still has the old limitation with different dividers, but it handles your case correctly.

The only difference is the `removingPunctuation()` method call.

```kotlin
class ReversedMaskTextChangedListener(
    format: String,
    customNotations: List<Notation> = emptyList(),
    autocomplete: Boolean = true,
    field: EditText,
    listener: TextWatcher? = null,
    valueListener: ValueListener? =null
) : MaskedTextChangedListener(
    format,
    customNotations,
    autocomplete,
    field,
    listener,
    valueListener
) {
    private val reversedMask: Mask = Mask.getOrCreate(format.reversedFormat(), customNotations)

    /**
     * Convenience constructor.
     */
    constructor(format: String, field: EditText, valueListener: ValueListener?) :
        this(format, field, null, valueListener)

    /**
     * Convenience constructor.
     */
    constructor(format: String, field: EditText, listener: TextWatcher?, valueListener: ValueListener?) :
        this(format, true, field, listener, valueListener)

    /**
     * Convenience constructor.
     */
    constructor(format: String, autocomplete: Boolean, field: EditText, listener: TextWatcher?, valueListener: ValueListener?) :
        this(format, emptyList(), autocomplete, field, listener, valueListener)

    override fun setText(text: String) {
        val result: Mask.Result =
            this.reversedMask.apply(
                CaretString(
                    text.reversed(),
                    text.length
                ),
                this.autocomplete
            )
        this.field.get()?.setText(result.formattedText.string.reversed())
        this.field.get()?.setSelection(result.formattedText.caretPosition)
        this.valueListener?.onTextChanged(result.complete, result.extractedValue.reversed())
    }

    override fun onTextChanged(text: CharSequence, cursorPosition: Int, before: Int, count: Int) {
        val isDeletion: Boolean = before > 0 && count == 0

        val oldText = text.toString()
        val oldCaretPosition =
            if (isDeletion)
                oldText.length - cursorPosition
            else
                oldText.length - (cursorPosition + count)

        val result: Mask.Result =
            this.reversedMask.apply(
                CaretString(
                    oldText.reversed().removingPunctuation(),
                    oldCaretPosition
                ),
                this.autocomplete && !isDeletion
            )
        val formattedText = result.formattedText.string

        this.afterText = formattedText.reversed()
        this.caretPosition = formattedText.length - result.formattedText.caretPosition

        this.valueListener?.onTextChanged(result.complete, result.extractedValue.reversed())
    }

    override fun onFocusChange(view: View?, hasFocus: Boolean) {
        if (this.autocomplete && hasFocus) {
            val text: String = if (this.field.get()?.text!!.isEmpty()) {
                ""
            } else {
                this.field.get()?.text.toString()
            }

            val result: Mask.Result =
                this.reversedMask.apply(
                    CaretString(
                        text.reversed(),
                        text.length
                    ),
                    this.autocomplete
                )
            this.field.get()?.setText(result.formattedText.string.reversed())
            this.field.get()?.setSelection(result.formattedText.caretPosition)
            this.valueListener?.onTextChanged(result.complete, result.extractedValue)
        }
    }

    private fun String.reversedFormat() = this.reversed()
        .replace("[\\", "\\]")
        .replace("]\\", "\\[")
        .replace("{\\", "\\}")
        .replace("}\\", "\\{")
        .map { c: Char ->
            when (c) {
                '[' -> ']'
                ']' -> '['
                '{' -> '}'
                '}' -> '{'
                else -> c
            }
        }.joinToString("")

    private fun String.removingPunctuation(): String {
        return this.replace(".", "").replace("-", "")
    }

}
```

**Comment by jesualex** [comment]
Excuse me @taflanidi 

I am testing the new class, I found that moving the cursor to the middle after the 7th digit and deleting or adding a digit generates the following exception:

```
    java.lang.IndexOutOfBoundsException: setSpan (-2 ... -2) starts before 0
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1276)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:690)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:683)
        at android.text.Selection.setSelection(Selection.java:76)
        at android.text.Selection.setSelection(Selection.java:87)
        at android.widget.EditText.setSelection(EditText.java:103)
        at com.redmadrobot.inputmask.MaskedTextChangedListener.afterTextChanged(MaskedTextChangedListener.kt:121)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:8242)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10421)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1224)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:844)
        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:198)
        at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:345)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:91)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

have you any idea?

**Comment by jesualex** [comment]
Dear @taflanidi 
I solved the problem, is ugly but works xD

```
class ReversedMaskTextChangedListener(
        format: String,
        customNotations: List<Notation> = emptyList(),
        autocomplete: Boolean = true,
        field: EditText,
        listener: TextWatcher? = null,
        valueListener: ValueListener? =null
) : MaskedTextChangedListener(
        format,
        customNotations,
        autocomplete,
        field,
        listener,
        valueListener
) {
    private val reversedMask: Mask = Mask.getOrCreate(format.reversedFormat(), customNotations)

    /**
     * Convenience constructor.
     */
    constructor(format: String, field: EditText, valueListener: ValueListener?) :
            this(format, field, null, valueListener)

    /**
     * Convenience constructor.
     */
    constructor(format: String, field: EditText, listener: TextWatcher?, valueListener: ValueListener?) :
            this(format, true, field, listener, valueListener)

    /**
     * Convenience constructor.
     */
    constructor(format: String, autocomplete: Boolean, field: EditText, listener: TextWatcher?, valueListener: ValueListener?) :
            this(format, emptyList(), autocomplete, field, listener, valueListener)

    override fun setText(text: String) {
        val result: Mask.Result =
                this.reversedMask.apply(
                        CaretString(
                                text.reversed(),
                                text.length
                        ),
                        this.autocomplete
                )
        this.field.get()?.setText(result.formattedText.string.reversed())
        this.field.get()?.setSelection(result.formattedText.caretPosition)
        this.valueListener?.onTextChanged(result.complete, result.extractedValue.reversed())
    }

    override fun onTextChanged(text: CharSequence, cursorPosition: Int, before: Int, count: Int) {
        val isDeletion: Boolean = before > 0 && count == 0

        val oldText = text.toString().reversed()
        val oldCaretPosition =
                if (isDeletion)
                    oldText.length - cursorPosition
                else
                    oldText.length - (cursorPosition + count)

        val result: Mask.Result =
                this.reversedMask.apply(
                        oldText.getCaret(oldCaretPosition),
                        this.autocomplete && !isDeletion
                )
        val formattedText = result.formattedText.string

        this.afterText = formattedText.reversed()
        this.caretPosition = formattedText.length - result.formattedText.caretPosition

        this.valueListener?.onTextChanged(result.complete, result.extractedValue.reversed())
    }

    override fun onFocusChange(view: View?, hasFocus: Boolean) {
        if (this.autocomplete && hasFocus) {
            val text: String = if (this.field.get()?.text!!.isEmpty()) {
                ""
            } else {
                this.field.get()?.text.toString()
            }

            val result: Mask.Result =
                    this.reversedMask.apply(
                            CaretString(
                                    text.reversed(),
                                    text.length
                            ),
                            this.autocomplete
                    )
            this.field.get()?.setText(result.formattedText.string.reversed())
            this.field.get()?.setSelection(result.formattedText.caretPosition)
            this.valueListener?.onTextChanged(result.complete, result.extractedValue)
        }
    }

    private fun String.reversedFormat() = this.reversed()
            .replace("[\\", "\\]")
            .replace("]\\", "\\[")
            .replace("{\\", "\\}")
            .replace("}\\", "\\{")
            .map { c: Char ->
                when (c) {
                    '[' -> ']'
                    ']' -> '['
                    '{' -> '}'
                    '}' -> '{'
                    else -> c
                }
            }.joinToString("")

    private fun String.getCaret(oldCaretPosition : Int): CaretString {
        var pos: Int = oldCaretPosition
        val text: String = this.mapIndexed {
            i: Int, c: Char ->
            if (c == '.' || c == '-') {
                if (i < oldCaretPosition) pos -= 1
                ""
            } else c
        }.joinToString ("")

        return CaretString(text, pos)
    }
}
```

**Comment by taflanidi** [comment]
Hey @jesualex,
I'm sorry for the delay.

Please don't call your solution ugly (-:
If it's stupid, but it works, it ain't stupid.

I'll be closing this issue a little bit later, and I'll create an another one, more concrete, issue regarding the works on our `ReversedMaskTextChangedListener`. Thanks for your contribution!
